/**
 * functions/_shared/catalog-index.js
 * ⚠ FICHIER GÉNÉRÉ AUTOMATIQUEMENT — ne pas éditer manuellement
 * Regénérer via : node scripts/build-catalog-index.js
 * (exécuté automatiquement à chaque build)
 */

// @ts-check

/** @type {Record<string, number>} */
export const CATALOG = {
  "al-fakher-crown-bar-30k-20mg": 19.9,
  "allume-charbon-chicha-tsar": 19.9,
  "allume-charbon-gaz-blackcoco-s": 24.9,
  "amazonien": 19.9,
  "amnesia-hydro-indoor-cbd": 4.9,
  "amnesia-hydro-indoor-cbd::2g": 9.8,
  "amnesia-hydro-indoor-cbd::4g": 19.6,
  "amnesia-hydro-indoor-cbd::8g": 39.2,
  "ananas-coco-50ml-le-petit-verger": 16.9,
  "ananas-coco-frais": 16.9,
  "baba-au-rhum-50-ml": 16.9,
  "balance-de-precision-hudson-300g-x-0-01g": 16.9,
  "balance-de-precision-java-100g-x-0-01g": 11.9,
  "banana-hydro-indoor-cbd": 4.9,
  "banana-hydro-indoor-cbd::2g": 9.8,
  "banana-hydro-indoor-cbd::4g": 19.6,
  "banana-hydro-indoor-cbd::8g": 39.2,
  "bang-en-verre-30-cm-percolateur": 19.9,
  "bang-verre-20-cm-percolateur": 16.9,
  "base-neutre-aromazon-vbase-50-50-1l-sans-nicotine": 9.9,
  "box-erato-230-smoktech": 29.9,
  "box-gen-se-vaporesso": 39.9,
  "box-voopoo-vinci-spark-100": 39.9,
  "brugnon-orange-sanguine-50-ml": 16.9,
  "bubba-kush-hydro-indoor-cbd": 4.9,
  "bubba-kush-hydro-indoor-cbd::2g": 9.8,
  "bubba-kush-hydro-indoor-cbd::4g": 19.6,
  "bubba-kush-hydro-indoor-cbd::8g": 39.2,
  "burn-baby-burn-indoor-cbd": 4.9,
  "burn-baby-burn-indoor-cbd::2g": 9.8,
  "burn-baby-burn-indoor-cbd::4g": 19.6,
  "burn-baby-burn-indoor-cbd::8g": 39.2,
  "cake-noisettes-50-ml": 16.9,
  "candy-hydro-indoor-cbd": 4.9,
  "candy-hydro-indoor-cbd::2g": 9.8,
  "candy-hydro-indoor-cbd::4g": 19.6,
  "candy-hydro-indoor-cbd::8g": 39.2,
  "cannele-50-ml": 16.9,
  "cassis-framboise-50ml-le-petit-verger": 16.9,
  "cassis-framboise-frais": 16.9,
  "cassis": 19.9,
  "cendrier-alien": 14.9,
  "cendrier-astronaute": 9.9,
  "cerise-pasteque-frais": 16.9,
  "charas-cbd": 4.9,
  "charas-cbd::2g": 9.8,
  "charas-cbd::4g": 19.6,
  "charas-cbd::8g": 39.2,
  "clearomiseur-zeus-nano-2-geekvape": 24.9,
  "clearomiseur-zeus-subohm-5-ml-geekvape": 29.9,
  "concentre-biggy-bear-30ml": 9.9,
  "corossol-peche-frais": 16.9,
  "dutch-punch-indoor-cbd": 4.9,
  "dutch-punch-indoor-cbd::2g": 9.8,
  "dutch-punch-indoor-cbd::4g": 19.6,
  "dutch-punch-indoor-cbd::8g": 39.2,
  "e-cg-50ml": 11.9,
  "e-liquide-jnr-10ml-20mg-sel-de-nicotine": 3.9,
  "eclair-vanille-50-ml": 16.9,
  "extract-crumble": 9.9,
  "extract-crumble::2g": 19.8,
  "extract-crumble::4g": 39.6,
  "extract-crumble::8g": 79.2,
  "frais-peche-litchi-frais": 16.9,
  "fraise-litchi": 16.9,
  "fraise-poire-50ml-le-petit-verger": 16.9,
  "fraise-poire-frais": 16.9,
  "fraise": 19.9,
  "fruit-du-dragon-fruits-rouges-frais": 16.9,
  "fruit-du-dragon-jaune-framboise-bleue-frais": 16.9,
  "fruit-du-serpent-grenade-frais": 16.9,
  "fruits-rouges": 19.9,
  "geekvape-zeus-nano-3": 24.9,
  "gelato-hydro-indoor-cbd": 4.9,
  "gelato-hydro-indoor-cbd::2g": 9.8,
  "gelato-hydro-indoor-cbd::4g": 19.6,
  "gelato-hydro-indoor-cbd::8g": 39.2,
  "goyave-coco": 16.9,
  "grinder-champignon-3-parties-metal-effet-holographique": 9.9,
  "grinder-gold": 9.9,
  "grinder-sensky-4-parties-en-aluminium": 9.9,
  "hash-primero": 4.9,
  "hash-primero::2g": 9.8,
  "hash-primero::4g": 19.6,
  "hash-primero::8g": 39.2,
  "jack-herer-hydro-indoor-cbd": 4.9,
  "jack-herer-hydro-indoor-cbd::2g": 9.8,
  "jack-herer-hydro-indoor-cbd::4g": 19.6,
  "jack-herer-hydro-indoor-cbd::8g": 39.2,
  "jnr-28000-puffs": 18.9,
  "jnr-32000-puffs": 19.9,
  "jnr-crystalglow-love-66-adalya": 19.9,
  "jnr-falcon-gem-30k": 19.9,
  "kit-box-gen-se-vaporesso-clearomiseur-zeus-nano-2-geek-vape": 64.9,
  "kit-gtx-one-pro-vaporesso": 49.9,
  "kit-q16-pro-plus-de-justfog": 39.9,
  "kiwi-cactus-frais": 16.9,
  "kiwi-mangue-50ml-le-petit-verger": 16.9,
  "kiwi-mangue-frais": 16.9,
  "l-elixir": 19.9,
  "le-druide": 19.9,
  "le-menthe-verte": 19.9,
  "le-peche": 19.9,
  "le-texan": 19.9,
  "le-vanille": 19.9,
  "lemon-hydro-indoor-cbd": 4.9,
  "lemon-hydro-indoor-cbd::2g": 9.8,
  "lemon-hydro-indoor-cbd::4g": 19.6,
  "lemon-hydro-indoor-cbd::8g": 39.2,
  "luxe-xr-max-2-vaporesso": 39.9,
  "melange-vegetal-bergamote": 6.9,
  "melange-vegetal-menthe": 6.9,
  "melange-vegetal-natura": 6.9,
  "melon-fraise-des-bois-frais": 16.9,
  "menthe-intense": 19.9,
  "moby-dick-hydro-indoor-cbd": 4.9,
  "moby-dick-hydro-indoor-cbd::2g": 9.8,
  "moby-dick-hydro-indoor-cbd::4g": 19.6,
  "moby-dick-hydro-indoor-cbd::8g": 39.2,
  "moon-rock-cbd-indoor": 7.9,
  "moon-rock-cbd-indoor::2g": 15.8,
  "moon-rock-cbd-indoor::4g": 31.6,
  "moon-rock-cbd-indoor::8g": 63.2,
  "mousse-chocolat-blanc-noisettes-50-ml": 16.9,
  "mure-myrtille-50ml-le-petit-verger": 16.9,
  "mure-myrtille-frais": 16.9,
  "nectarine-fruit-du-dragon-50ml-le-petit-verger": 16.9,
  "nectarine-fruit-du-dragon-frais": 16.9,
  "noisette": 19.9,
  "palet-breton-50-ml": 16.9,
  "pasteque-citron-vert": 16.9,
  "pasteque-melon-frais": 16.9,
  "peche-litchi-50ml-le-petit-verger": 16.9,
  "plateau-beuz-arctic-grower": 4.99,
  "plateau-beuz-crazy-koala": 4.99,
  "plateau-beuz-purple-gorilla": 4.99,
  "plateau-euphoria": 9.9,
  "plateau-gangsta-panda": 6.9,
  "pod-de-remplacement-aerox-32k-jnr": 9.9,
  "pod-recharge": 9.9,
  "pollen-d-amnesia-100-cbd": 4.2,
  "pollen-d-amnesia-100-cbd::2g": 8.4,
  "pollen-d-amnesia-100-cbd::4g": 16.8,
  "pollen-d-amnesia-100-cbd::8g": 33.6,
  "pollen-d-or-100-cbd": 4.2,
  "pollen-d-or-100-cbd::2g": 8.4,
  "pollen-d-or-100-cbd::4g": 16.8,
  "pollen-d-or-100-cbd::8g": 33.6,
  "pomme-citron-50ml-le-petit-verger": 16.9,
  "pomme-citron-frais": 16.9,
  "pomme-rouge-pomme-verte": 16.9,
  "puff-30k-hyper-max-crown-bar-by-al-fakher": 19.9,
  "puff-adalya-30k": 19.9,
  "raisin-rouge-grenade": 16.9,
  "riz-au-lait-50-ml": 16.9,
  "robin-cherry-cbd": 6.9,
  "robin-cherry-cbd::2g": 13.8,
  "robin-cherry-cbd::4g": 27.6,
  "robin-cherry-cbd::8g": 55.2,
  "small-bud-lemon": 0.99,
  "small-bud-lemon::2g": 1.98,
  "small-bud-lemon::4g": 3.96,
  "small-bud-lemon::8g": 7.92,
  "small-bud-strawberry": 0.99,
  "small-bud-strawberry::2g": 1.98,
  "small-bud-strawberry::4g": 3.96,
  "small-bud-strawberry::8g": 7.92,
  "snowing-in-dam": 4.9,
  "spliff-box-l": 19.9,
  "spliff-box-m": 16.9,
  "starbuzz-ultra-max-25k": 19.9,
  "tiramisu-cafe-50-ml": 16.9,
  "vaporesso-vibe-se-2": 16.9,
  "vaporesso-vibe-se": 9.9,
  "wiz": 19.9,
  "xros-5-mini-vaporesso": 19.9,
  "xros-5-vaporesso": 24.9,
  "zpluse-jnr-42k": 19.9
};

/**
 * Stocks disponibles, mêmes clés que CATALOG.
 * C'est la seule limite de quantité : il n'y a pas de plafond arbitraire.
 * @type {Record<string, number>}
 */
export const STOCKS = {
  "al-fakher-crown-bar-30k-20mg": 10,
  "allume-charbon-chicha-tsar": 10,
  "allume-charbon-gaz-blackcoco-s": 10,
  "amazonien": 10,
  "amnesia-hydro-indoor-cbd": 10,
  "amnesia-hydro-indoor-cbd::2g": 10,
  "amnesia-hydro-indoor-cbd::4g": 10,
  "amnesia-hydro-indoor-cbd::8g": 10,
  "ananas-coco-50ml-le-petit-verger": 10,
  "ananas-coco-frais": 10,
  "baba-au-rhum-50-ml": 10,
  "balance-de-precision-hudson-300g-x-0-01g": 10,
  "balance-de-precision-java-100g-x-0-01g": 10,
  "banana-hydro-indoor-cbd": 10,
  "banana-hydro-indoor-cbd::2g": 10,
  "banana-hydro-indoor-cbd::4g": 10,
  "banana-hydro-indoor-cbd::8g": 10,
  "bang-en-verre-30-cm-percolateur": 10,
  "bang-verre-20-cm-percolateur": 10,
  "base-neutre-aromazon-vbase-50-50-1l-sans-nicotine": 10,
  "box-erato-230-smoktech": 10,
  "box-gen-se-vaporesso": 10,
  "box-voopoo-vinci-spark-100": 10,
  "brugnon-orange-sanguine-50-ml": 10,
  "bubba-kush-hydro-indoor-cbd": 10,
  "bubba-kush-hydro-indoor-cbd::2g": 10,
  "bubba-kush-hydro-indoor-cbd::4g": 10,
  "bubba-kush-hydro-indoor-cbd::8g": 10,
  "burn-baby-burn-indoor-cbd": 10,
  "burn-baby-burn-indoor-cbd::2g": 10,
  "burn-baby-burn-indoor-cbd::4g": 10,
  "burn-baby-burn-indoor-cbd::8g": 10,
  "cake-noisettes-50-ml": 10,
  "candy-hydro-indoor-cbd": 10,
  "candy-hydro-indoor-cbd::2g": 10,
  "candy-hydro-indoor-cbd::4g": 10,
  "candy-hydro-indoor-cbd::8g": 10,
  "cannele-50-ml": 10,
  "cassis-framboise-50ml-le-petit-verger": 10,
  "cassis-framboise-frais": 10,
  "cassis": 10,
  "cendrier-alien": 10,
  "cendrier-astronaute": 10,
  "cerise-pasteque-frais": 10,
  "charas-cbd": 10,
  "charas-cbd::2g": 10,
  "charas-cbd::4g": 10,
  "charas-cbd::8g": 10,
  "clearomiseur-zeus-nano-2-geekvape": 10,
  "clearomiseur-zeus-subohm-5-ml-geekvape": 10,
  "concentre-biggy-bear-30ml": 10,
  "corossol-peche-frais": 10,
  "dutch-punch-indoor-cbd": 10,
  "dutch-punch-indoor-cbd::2g": 10,
  "dutch-punch-indoor-cbd::4g": 10,
  "dutch-punch-indoor-cbd::8g": 10,
  "e-cg-50ml": 10,
  "e-liquide-jnr-10ml-20mg-sel-de-nicotine": 10,
  "eclair-vanille-50-ml": 10,
  "extract-crumble": 10,
  "extract-crumble::2g": 10,
  "extract-crumble::4g": 10,
  "extract-crumble::8g": 10,
  "frais-peche-litchi-frais": 10,
  "fraise-litchi": 10,
  "fraise-poire-50ml-le-petit-verger": 10,
  "fraise-poire-frais": 10,
  "fraise": 10,
  "fruit-du-dragon-fruits-rouges-frais": 10,
  "fruit-du-dragon-jaune-framboise-bleue-frais": 10,
  "fruit-du-serpent-grenade-frais": 10,
  "fruits-rouges": 10,
  "geekvape-zeus-nano-3": 10,
  "gelato-hydro-indoor-cbd": 10,
  "gelato-hydro-indoor-cbd::2g": 10,
  "gelato-hydro-indoor-cbd::4g": 10,
  "gelato-hydro-indoor-cbd::8g": 10,
  "goyave-coco": 10,
  "grinder-champignon-3-parties-metal-effet-holographique": 10,
  "grinder-gold": 10,
  "grinder-sensky-4-parties-en-aluminium": 10,
  "hash-primero": 10,
  "hash-primero::2g": 10,
  "hash-primero::4g": 10,
  "hash-primero::8g": 10,
  "jack-herer-hydro-indoor-cbd": 10,
  "jack-herer-hydro-indoor-cbd::2g": 10,
  "jack-herer-hydro-indoor-cbd::4g": 10,
  "jack-herer-hydro-indoor-cbd::8g": 10,
  "jnr-28000-puffs": 10,
  "jnr-32000-puffs": 10,
  "jnr-crystalglow-love-66-adalya": 10,
  "jnr-falcon-gem-30k": 10,
  "kit-box-gen-se-vaporesso-clearomiseur-zeus-nano-2-geek-vape": 10,
  "kit-gtx-one-pro-vaporesso": 10,
  "kit-q16-pro-plus-de-justfog": 10,
  "kiwi-cactus-frais": 10,
  "kiwi-mangue-50ml-le-petit-verger": 10,
  "kiwi-mangue-frais": 10,
  "l-elixir": 10,
  "le-druide": 10,
  "le-menthe-verte": 10,
  "le-peche": 10,
  "le-texan": 10,
  "le-vanille": 10,
  "lemon-hydro-indoor-cbd": 10,
  "lemon-hydro-indoor-cbd::2g": 10,
  "lemon-hydro-indoor-cbd::4g": 10,
  "lemon-hydro-indoor-cbd::8g": 10,
  "luxe-xr-max-2-vaporesso": 10,
  "melange-vegetal-bergamote": 10,
  "melange-vegetal-menthe": 10,
  "melange-vegetal-natura": 10,
  "melon-fraise-des-bois-frais": 10,
  "menthe-intense": 10,
  "moby-dick-hydro-indoor-cbd": 10,
  "moby-dick-hydro-indoor-cbd::2g": 10,
  "moby-dick-hydro-indoor-cbd::4g": 10,
  "moby-dick-hydro-indoor-cbd::8g": 10,
  "moon-rock-cbd-indoor": 10,
  "moon-rock-cbd-indoor::2g": 10,
  "moon-rock-cbd-indoor::4g": 10,
  "moon-rock-cbd-indoor::8g": 10,
  "mousse-chocolat-blanc-noisettes-50-ml": 10,
  "mure-myrtille-50ml-le-petit-verger": 10,
  "mure-myrtille-frais": 10,
  "nectarine-fruit-du-dragon-50ml-le-petit-verger": 10,
  "nectarine-fruit-du-dragon-frais": 10,
  "noisette": 10,
  "palet-breton-50-ml": 10,
  "pasteque-citron-vert": 10,
  "pasteque-melon-frais": 10,
  "peche-litchi-50ml-le-petit-verger": 10,
  "plateau-beuz-arctic-grower": 10,
  "plateau-beuz-crazy-koala": 10,
  "plateau-beuz-purple-gorilla": 10,
  "plateau-euphoria": 10,
  "plateau-gangsta-panda": 10,
  "pod-de-remplacement-aerox-32k-jnr": 10,
  "pod-recharge": 10,
  "pollen-d-amnesia-100-cbd": 10,
  "pollen-d-amnesia-100-cbd::2g": 10,
  "pollen-d-amnesia-100-cbd::4g": 10,
  "pollen-d-amnesia-100-cbd::8g": 10,
  "pollen-d-or-100-cbd": 10,
  "pollen-d-or-100-cbd::2g": 10,
  "pollen-d-or-100-cbd::4g": 10,
  "pollen-d-or-100-cbd::8g": 10,
  "pomme-citron-50ml-le-petit-verger": 10,
  "pomme-citron-frais": 10,
  "pomme-rouge-pomme-verte": 10,
  "puff-30k-hyper-max-crown-bar-by-al-fakher": 10,
  "puff-adalya-30k": 10,
  "raisin-rouge-grenade": 10,
  "riz-au-lait-50-ml": 10,
  "robin-cherry-cbd": 10,
  "robin-cherry-cbd::2g": 10,
  "robin-cherry-cbd::4g": 10,
  "robin-cherry-cbd::8g": 10,
  "small-bud-lemon": 10,
  "small-bud-lemon::2g": 10,
  "small-bud-lemon::4g": 10,
  "small-bud-lemon::8g": 10,
  "small-bud-strawberry": 10,
  "small-bud-strawberry::2g": 10,
  "small-bud-strawberry::4g": 10,
  "small-bud-strawberry::8g": 10,
  "snowing-in-dam": 10,
  "spliff-box-l": 10,
  "spliff-box-m": 10,
  "starbuzz-ultra-max-25k": 10,
  "tiramisu-cafe-50-ml": 10,
  "vaporesso-vibe-se-2": 10,
  "vaporesso-vibe-se": 10,
  "wiz": 10,
  "xros-5-mini-vaporesso": 10,
  "xros-5-vaporesso": 10,
  "zpluse-jnr-42k": 10
};

/**
 * Produits déclinés en variantes (grammages, saveurs).
 * Pour ceux-là, un label absent du catalogue est une erreur, pas un cas de repli.
 * @type {Set<string>}
 */
export const PRODUITS_A_VARIANTES = new Set([
  "amnesia-hydro-indoor-cbd",
  "banana-hydro-indoor-cbd",
  "bubba-kush-hydro-indoor-cbd",
  "burn-baby-burn-indoor-cbd",
  "candy-hydro-indoor-cbd",
  "charas-cbd",
  "dutch-punch-indoor-cbd",
  "extract-crumble",
  "gelato-hydro-indoor-cbd",
  "hash-primero",
  "jack-herer-hydro-indoor-cbd",
  "lemon-hydro-indoor-cbd",
  "moby-dick-hydro-indoor-cbd",
  "moon-rock-cbd-indoor",
  "pollen-d-amnesia-100-cbd",
  "pollen-d-or-100-cbd",
  "robin-cherry-cbd",
  "small-bud-lemon",
  "small-bud-strawberry"
]);

/**
 * Renvoie le prix serveur vérifié pour un article du panier.
 *
 * Règles :
 *  - label connu           → prix de la variante
 *  - label inconnu sur un produit à variantes → null (article rejeté)
 *  - pas de label          → prix de base, si le produit en a un
 *
 * @param {string} id          - ID produit (slug)
 * @param {string|null} label  - Label de variante (ou null pour le prix de base)
 * @returns {number|null}       - Prix TTC en euros, ou null si introuvable
 */
export function lookupPrice(id, label) {
  if (label) {
    const key = `${id}::${label}`;
    if (key in CATALOG) return CATALOG[key];
    // Label fourni mais inconnu : on refuse plutôt que de facturer le prix de base
    if (PRODUITS_A_VARIANTES.has(id)) return null;
  }
  if (id in CATALOG) return CATALOG[id];
  return null;
}

/**
 * Quantité disponible pour un article, variante comprise.
 *
 * Un article inconnu renvoie 0 plutôt que null : l'appelant n'a pas à
 * distinguer « inconnu » de « épuisé », les deux interdisent la vente.
 *
 * @param {string} id
 * @param {string|null} label
 * @returns {number} quantité commandable, 0 si indisponible
 */
export function lookupStock(id, label) {
  if (label) {
    const key = `${id}::${label}`;
    if (key in STOCKS) return STOCKS[key];
    if (PRODUITS_A_VARIANTES.has(id)) return 0;
  }
  return id in STOCKS ? STOCKS[id] : 0;
}
