/**
 * functions/_shared/catalog-index.js
 * ⚠ FICHIER GÉNÉRÉ AUTOMATIQUEMENT — ne pas éditer manuellement
 * Regénérer via : node scripts/build-catalog-index.js
 * (exécuté automatiquement à chaque build)
 */

// @ts-check

/** @type {Record<string, number>} */
export const CATALOG = {
  "al-fakher-crown-bar-30k-20mg": 19.9,
  "allume-charbon-chicha-tsar": 19.9,
  "allume-charbon-gaz-blackcoco-s": 24.9,
  "amazonien": 19.9,
  "amnesia-hydro-indoor-cbd": 4.9,
  "amnesia-hydro-indoor-cbd::1g": 4.9,
  "amnesia-hydro-indoor-cbd::3g": 14.7,
  "amnesia-hydro-indoor-cbd::5g": 24.5,
  "amnesia-hydro-indoor-cbd::10g": 49,
  "ananas-coco-50ml-le-petit-verger": 16.9,
  "ananas-coco-frais": 16.9,
  "baba-au-rhum-50-ml": 16.9,
  "balance-de-precision-hudson-300g-x-0-01g": 16.9,
  "balance-de-precision-java-100g-x-0-01g": 11.9,
  "banana-hydro-indoor-cbd": 4.9,
  "banana-hydro-indoor-cbd::1g": 4.9,
  "banana-hydro-indoor-cbd::3g": 14.7,
  "banana-hydro-indoor-cbd::5g": 24.5,
  "banana-hydro-indoor-cbd::10g": 49,
  "bang-en-verre-30-cm-percolateur": 19.9,
  "bang-verre-20-cm-percolateur": 16.9,
  "base-neutre-aromazon-vbase-50-50-1l-sans-nicotine": 9.9,
  "box-erato-230-smoktech": 29.9,
  "box-gen-se-vaporesso": 39.9,
  "box-voopoo-vinci-spark-100": 39.9,
  "brugnon-orange-sanguine-50-ml": 16.9,
  "bubba-kush-hydro-indoor-cbd": 4.9,
  "bubba-kush-hydro-indoor-cbd::1g": 4.9,
  "bubba-kush-hydro-indoor-cbd::3g": 14.7,
  "bubba-kush-hydro-indoor-cbd::5g": 24.5,
  "bubba-kush-hydro-indoor-cbd::10g": 49,
  "burn-baby-burn-indoor-cbd": 4.9,
  "burn-baby-burn-indoor-cbd::1g": 4.9,
  "burn-baby-burn-indoor-cbd::3g": 14.7,
  "burn-baby-burn-indoor-cbd::5g": 24.5,
  "burn-baby-burn-indoor-cbd::10g": 49,
  "cake-noisettes-50-ml": 16.9,
  "candy-hydro-indoor-cbd": 4.9,
  "candy-hydro-indoor-cbd::1g": 4.9,
  "candy-hydro-indoor-cbd::3g": 14.7,
  "candy-hydro-indoor-cbd::5g": 24.5,
  "candy-hydro-indoor-cbd::10g": 49,
  "cannele-50-ml": 16.9,
  "cassis-framboise-50ml-le-petit-verger": 16.9,
  "cassis-framboise-frais": 16.9,
  "cassis": 19.9,
  "cendrier-alien": 14.9,
  "cendrier-astronaute": 9.9,
  "cerise-pasteque-frais": 16.9,
  "charas-cbd": 4.9,
  "charas-cbd::1g": 4.9,
  "charas-cbd::3g": 14.7,
  "charas-cbd::5g": 24.5,
  "charas-cbd::10g": 49,
  "charbon-fresh-coco-suprem-1kg": 6.9,
  "charbons-tom-cococha-gold-1kg": 6.9,
  "chicha-celeste-edition-black": 59.9,
  "chicha-dum-boost-l-d01": 89.9,
  "chicha-dum-boost-m-d02": 74.9,
  "chicha-el-badia-z6": 149.9,
  "chicha-tsar-h-one-evolution": 109,
  "clearomiseur-zeus-nano-2-geekvape": 24.9,
  "clearomiseur-zeus-subohm-5-ml-geekvape": 29.9,
  "concentre-biggy-bear-30ml": 9.9,
  "corossol-peche-frais": 16.9,
  "dschinni-nero-glass-pro": 24.9,
  "dutch-punch-indoor-cbd": 4.9,
  "dutch-punch-indoor-cbd::1g": 4.9,
  "dutch-punch-indoor-cbd::3g": 14.7,
  "dutch-punch-indoor-cbd::5g": 24.5,
  "dutch-punch-indoor-cbd::10g": 49,
  "e-cg-50ml": 11.9,
  "e-liquide-jnr-10ml-20mg-sel-de-nicotine": 3.9,
  "eclair-vanille-50-ml": 16.9,
  "el-badia-fusion": 49.9,
  "extract-crumble": 9.9,
  "extract-crumble::1g": 9.9,
  "extract-crumble::3g": 29.7,
  "extract-crumble::5g": 49.5,
  "extract-crumble::10g": 99,
  "foyer-ceramique-blanche": 14.9,
  "foyer-dum-phunnel": 11.9,
  "foyer-el-badia-kalys": 14.9,
  "foyer-russe-ceramique-kaloud": 29.9,
  "foyer-russe-kaloud": 29.9,
  "frais-peche-litchi-frais": 16.9,
  "fraise-litchi": 16.9,
  "fraise-poire-50ml-le-petit-verger": 16.9,
  "fraise-poire-frais": 16.9,
  "fraise": 19.9,
  "fruit-du-dragon-fruits-rouges-frais": 16.9,
  "fruit-du-dragon-jaune-framboise-bleue-frais": 16.9,
  "fruit-du-serpent-grenade-frais": 16.9,
  "fruits-rouges": 19.9,
  "geekvape-zeus-nano-3": 24.9,
  "gelato-hydro-indoor-cbd": 4.9,
  "gelato-hydro-indoor-cbd::1g": 4.9,
  "gelato-hydro-indoor-cbd::3g": 14.7,
  "gelato-hydro-indoor-cbd::5g": 24.5,
  "gelato-hydro-indoor-cbd::10g": 49,
  "goyave-coco": 16.9,
  "grinder-champignon-3-parties-metal-effet-holographique": 9.9,
  "grinder-gold": 9.9,
  "grinder-sensky-4-parties-en-aluminium": 9.9,
  "hash-primero": 4.9,
  "hash-primero::1g": 4.9,
  "hash-primero::3g": 14.7,
  "hash-primero::5g": 24.5,
  "hash-primero::10g": 49,
  "jack-herer-hydro-indoor-cbd": 4.9,
  "jack-herer-hydro-indoor-cbd::1g": 4.9,
  "jack-herer-hydro-indoor-cbd::3g": 14.7,
  "jack-herer-hydro-indoor-cbd::5g": 24.5,
  "jack-herer-hydro-indoor-cbd::10g": 49,
  "jnr-28000-puffs": 18.9,
  "jnr-32000-puffs": 19.9,
  "jnr-crystalglow-love-66-adalya": 19.9,
  "jnr-falcon-gem-30k": 19.9,
  "kaloud-i": 19.9,
  "kit-box-gen-se-vaporesso-clearomiseur-zeus-nano-2-geek-vape": 64.9,
  "kit-gtx-one-pro-vaporesso": 49.9,
  "kit-q16-pro-plus-de-justfog": 39.9,
  "kiwi-cactus-frais": 16.9,
  "kiwi-mangue-50ml-le-petit-verger": 16.9,
  "kiwi-mangue-frais": 16.9,
  "l-elixir": 19.9,
  "le-druide": 19.9,
  "le-menthe-verte": 19.9,
  "le-peche": 19.9,
  "le-texan": 19.9,
  "le-vanille": 19.9,
  "lemon-hydro-indoor-cbd": 4.9,
  "lemon-hydro-indoor-cbd::1g": 4.9,
  "lemon-hydro-indoor-cbd::3g": 14.7,
  "lemon-hydro-indoor-cbd::5g": 24.5,
  "lemon-hydro-indoor-cbd::10g": 49,
  "luxe-xr-max-2-vaporesso": 39.9,
  "manche-molotov-x-xl": 11.9,
  "melange-vegetal-bergamote": 6.9,
  "melange-vegetal-menthe": 6.9,
  "melange-vegetal-natura": 6.9,
  "melon-fraise-des-bois-frais": 16.9,
  "menthe-intense": 19.9,
  "moby-dick-hydro-indoor-cbd": 4.9,
  "moby-dick-hydro-indoor-cbd::1g": 4.9,
  "moby-dick-hydro-indoor-cbd::3g": 14.7,
  "moby-dick-hydro-indoor-cbd::5g": 24.5,
  "moby-dick-hydro-indoor-cbd::10g": 49,
  "moon-rock-cbd-indoor": 7.9,
  "moon-rock-cbd-indoor::1g": 7.9,
  "moon-rock-cbd-indoor::3g": 23.7,
  "moon-rock-cbd-indoor::5g": 39.5,
  "moon-rock-cbd-indoor::10g": 79,
  "mousse-chocolat-blanc-noisettes-50-ml": 16.9,
  "mure-myrtille-50ml-le-petit-verger": 16.9,
  "mure-myrtille-frais": 16.9,
  "nectarine-fruit-du-dragon-50ml-le-petit-verger": 16.9,
  "nectarine-fruit-du-dragon-frais": 16.9,
  "noisette": 19.9,
  "palet-breton-50-ml": 16.9,
  "pasteque-citron-vert": 16.9,
  "pasteque-melon-frais": 16.9,
  "peche-litchi-50ml-le-petit-verger": 16.9,
  "pinces-a-charbon-dschinni": 6.9,
  "plateau-beuz-arctic-grower": 4.99,
  "plateau-beuz-crazy-koala": 4.99,
  "plateau-beuz-purple-gorilla": 4.99,
  "plateau-euphoria": 9.9,
  "plateau-gangsta-panda": 6.9,
  "pod-de-remplacement-aerox-32k-jnr": 9.9,
  "pod-recharge": 9.9,
  "pollen-d-amnesia-100-cbd": 4.2,
  "pollen-d-amnesia-100-cbd::1g": 4.2,
  "pollen-d-amnesia-100-cbd::3g": 12.6,
  "pollen-d-amnesia-100-cbd::5g": 21,
  "pollen-d-amnesia-100-cbd::10g": 42,
  "pollen-d-or-100-cbd": 4.2,
  "pollen-d-or-100-cbd::1g": 4.2,
  "pollen-d-or-100-cbd::3g": 12.6,
  "pollen-d-or-100-cbd::5g": 21,
  "pollen-d-or-100-cbd::10g": 42,
  "pomme-citron-50ml-le-petit-verger": 16.9,
  "pomme-citron-frais": 16.9,
  "pomme-rouge-pomme-verte": 16.9,
  "puff-30k-hyper-max-crown-bar-by-al-fakher": 19.9,
  "puff-adalya-30k": 19.9,
  "quasar-raas-2": 69.9,
  "raisin-rouge-grenade": 16.9,
  "riz-au-lait-50-ml": 16.9,
  "robin-cherry-cbd": 6.9,
  "robin-cherry-cbd::1g": 6.9,
  "robin-cherry-cbd::3g": 20.7,
  "robin-cherry-cbd::5g": 34.5,
  "robin-cherry-cbd::10g": 69,
  "small-bud-lemon": 0.99,
  "small-bud-lemon::1g": 0.99,
  "small-bud-lemon::3g": 2.97,
  "small-bud-lemon::5g": 4.95,
  "small-bud-lemon::10g": 9.9,
  "small-bud-strawberry": 0.99,
  "small-bud-strawberry::1g": 0.99,
  "small-bud-strawberry::3g": 2.97,
  "small-bud-strawberry::5g": 4.95,
  "small-bud-strawberry::10g": 9.9,
  "smoke-island": 16.9,
  "snowing-in-dam": 4.9,
  "spliff-box-l": 19.9,
  "spliff-box-m": 16.9,
  "starbuzz-ultra-max-25k": 19.9,
  "tiramisu-cafe-50-ml": 16.9,
  "tuyaux-silicones": 6.9,
  "vaporesso-vibe-se-2": 16.9,
  "vaporesso-vibe-se": 9.9,
  "wiz": 19.9,
  "xros-5-mini-vaporesso": 19.9,
  "xros-5-vaporesso": 24.9,
  "zpluse-jnr-42k": 19.9
};

/**
 * Renvoie le prix serveur vérifié pour un article du panier.
 * @param {string} id          - ID produit (slug)
 * @param {string|null} label  - Label de variante (ou null pour le prix de base)
 * @returns {number|null}       - Prix TTC en euros, ou null si introuvable
 */
export function lookupPrice(id, label) {
  if (label) {
    const key = `${id}::${label}`;
    if (key in CATALOG) return CATALOG[key];
  }
  if (id in CATALOG) return CATALOG[id];
  return null;
}
