-- ═══════════════════════════════════════════════════════════════════════════
-- GÉNÉRÉ AUTOMATIQUEMENT par scripts/seed-stocks.js — ne pas éditer
-- 159 entrées de stock, 121 produits actifs
--
-- Rejouable sans risque : INSERT OR IGNORE laisse intacts les stocks déjà
-- présents. Ce fichier ne sert qu'à faire entrer les NOUVEAUX produits.
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('al-fakher-crown-bar-30k-20mg', 10, 0, 'Al Fakher Crown Bar 30K 20MG', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('allume-charbon-chicha-tsar', 10, 0, 'Allume charbon Chicha Tsar', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('allume-charbon-gaz-blackcoco-s', 10, 0, 'Allume charbon Gaz Blackcoco’s', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('amazonien', 10, 0, 'Amazonien', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('amnesia-hydro-indoor-cbd::2g', 10, 0, 'Amnésia Hydro Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('amnesia-hydro-indoor-cbd::4g', 10, 0, 'Amnésia Hydro Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('amnesia-hydro-indoor-cbd::8g', 10, 0, 'Amnésia Hydro Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('ananas-coco-50ml-le-petit-verger', 10, 0, 'Ananas Coco 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('ananas-coco-frais', 10, 0, 'Ananas Coco FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('baba-au-rhum-50-ml', 10, 0, 'Baba au Rhum – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('balance-de-precision-hudson-300g-x-0-01g', 10, 0, 'Balance de précision HUDSON 300g x 0.01g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('balance-de-precision-java-100g-x-0-01g', 10, 0, 'Balance de précision JAVA 100g x 0.01g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('banana-hydro-indoor-cbd::2g', 10, 0, 'Banana Hydro Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('banana-hydro-indoor-cbd::4g', 10, 0, 'Banana Hydro Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('banana-hydro-indoor-cbd::8g', 10, 0, 'Banana Hydro Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('bang-en-verre-30-cm-percolateur', 10, 0, 'Bang en Verre 30 cm Percolateur', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('bang-verre-20-cm-percolateur', 10, 0, 'Bang verre 20 cm Percolateur', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('base-neutre-aromazon-vbase-50-50-1l-sans-nicotine', 10, 0, 'Base Neutre Aromazon VBASE 50/50 – 1L (Sans Nicotine)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('box-erato-230-smoktech', 10, 0, 'Box Erato 230 – Smoktech', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('box-gen-se-vaporesso', 10, 0, 'Box Gen SE Vaporesso', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('box-voopoo-vinci-spark-100', 10, 0, 'Box Voopoo Vinci Spark 100', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('brugnon-orange-sanguine-50-ml', 10, 0, 'Brugnon – Orange sanguine 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('bubba-kush-hydro-indoor-cbd::2g', 10, 0, 'Bubba Kush Hydro Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('bubba-kush-hydro-indoor-cbd::4g', 10, 0, 'Bubba Kush Hydro Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('bubba-kush-hydro-indoor-cbd::8g', 10, 0, 'Bubba Kush Hydro Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('burn-baby-burn-indoor-cbd::2g', 10, 0, 'Burn Baby Burn Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('burn-baby-burn-indoor-cbd::4g', 10, 0, 'Burn Baby Burn Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('burn-baby-burn-indoor-cbd::8g', 10, 0, 'Burn Baby Burn Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cake-noisettes-50-ml', 10, 0, 'Cake Noisettes – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('candy-hydro-indoor-cbd::2g', 10, 0, 'Candy Hydro Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('candy-hydro-indoor-cbd::4g', 10, 0, 'Candy Hydro Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('candy-hydro-indoor-cbd::8g', 10, 0, 'Candy Hydro Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cannele-50-ml', 10, 0, 'Cannelé – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cassis-framboise-50ml-le-petit-verger', 10, 0, 'Cassis Framboise 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cassis-framboise-frais', 10, 0, 'Cassis Framboise FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cassis', 10, 0, 'Cassis', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cendrier-alien', 10, 0, 'Cendrier Alien', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cendrier-astronaute', 10, 0, 'Cendrier Astronaute', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cerise-pasteque-frais', 10, 0, 'Cerise Pastéque FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('charas-cbd::2g', 10, 0, 'Charas CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('charas-cbd::4g', 10, 0, 'Charas CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('charas-cbd::8g', 10, 0, 'Charas CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('clearomiseur-zeus-nano-2-geekvape', 10, 0, 'Clearomiseur Zeus Nano 2 GeekVape', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('clearomiseur-zeus-subohm-5-ml-geekvape', 10, 0, 'Clearomiseur Zeus Subohm 5 ml Geekvape', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('concentre-biggy-bear-30ml', 10, 0, 'Concentré Biggy bear 30ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('corossol-peche-frais', 10, 0, 'Corossol Pêche FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('dutch-punch-indoor-cbd::2g', 10, 0, 'Dutch Punch Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('dutch-punch-indoor-cbd::4g', 10, 0, 'Dutch Punch Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('dutch-punch-indoor-cbd::8g', 10, 0, 'Dutch Punch Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-cg-50ml', 10, 0, 'E-CG 50ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('eclair-vanille-50-ml', 10, 0, 'Éclair Vanille – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('extract-crumble::2g', 10, 0, 'Extract Crumble — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('extract-crumble::4g', 10, 0, 'Extract Crumble — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('extract-crumble::8g', 10, 0, 'Extract Crumble — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('frais-peche-litchi-frais', 10, 0, 'Frais Pêche – Litchi FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fraise-litchi', 10, 0, 'Fraise – Litchi', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fraise-poire-50ml-le-petit-verger', 10, 0, 'Fraise Poire 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fraise-poire-frais', 10, 0, 'Fraise Poire FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fraise', 10, 0, 'Fraise', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fruit-du-dragon-fruits-rouges-frais', 10, 0, 'Fruit Du Dragon - Fruits Rouges FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fruit-du-dragon-jaune-framboise-bleue-frais', 10, 0, 'Fruit du Dragon Jaune – Framboise Bleue FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fruit-du-serpent-grenade-frais', 10, 0, 'Fruit du Serpent – Grenade FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fruits-rouges', 10, 0, 'Fruits rouges', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('geekvape-zeus-nano-3', 10, 0, 'Geekvape Zeus Nano 3', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('gelato-hydro-indoor-cbd::2g', 10, 0, 'Gelato Hydro Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('gelato-hydro-indoor-cbd::4g', 10, 0, 'Gelato Hydro Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('gelato-hydro-indoor-cbd::8g', 10, 0, 'Gelato Hydro Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('goyave-coco', 10, 0, 'Goyave - coco', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('grinder-champignon-3-parties-metal-effet-holographique', 10, 0, 'Grinder Champignon – 3 parties métal effet holographique', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('grinder-gold', 10, 0, 'Grinder Gold', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('grinder-sensky-4-parties-en-aluminium', 10, 0, 'Grinder Sensky – 4 parties en aluminium', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('hash-primero::2g', 10, 0, 'Hash Primero — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('hash-primero::4g', 10, 0, 'Hash Primero — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('hash-primero::8g', 10, 0, 'Hash Primero — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jack-herer-hydro-indoor-cbd::2g', 10, 0, 'Jack Herer Hydro Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jack-herer-hydro-indoor-cbd::4g', 10, 0, 'Jack Herer Hydro Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jack-herer-hydro-indoor-cbd::8g', 10, 0, 'Jack Herer Hydro Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jnr-28000-puffs', 10, 0, 'JNR 28000 Puffs', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jnr-32000-puffs', 10, 0, 'JNR 32000 Puffs', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jnr-crystalglow-love-66-adalya', 10, 0, 'JNR CRYSTALGLOW LOVE 66 Adalya', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jnr-falcon-gem-30k', 10, 0, 'JNR Falcon Gem+ 30K', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kit-box-gen-se-vaporesso-clearomiseur-zeus-nano-2-geek-vape', 10, 0, 'Kit Box Gen SE Vaporesso + Clearomiseur Zeus Nano 2 Geek Vape', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kit-gtx-one-pro-vaporesso', 10, 0, 'Kit GTX One Pro Vaporesso', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kit-q16-pro-plus-de-justfog', 10, 0, 'Kit Q16 Pro Plus de Justfog', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kiwi-cactus-frais', 10, 0, 'Kiwi – Cactus FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kiwi-mangue-50ml-le-petit-verger', 10, 0, 'Kiwi Mangue 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kiwi-mangue-frais', 10, 0, 'Kiwi – Mangue FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('l-elixir', 10, 0, 'L''elixir', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-druide', 10, 0, 'Le Druide', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-menthe-verte', 10, 0, 'Le Menthe Verte', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-peche', 10, 0, 'Le Pêche', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-texan', 10, 0, 'Le Texan', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-vanille', 10, 0, 'Le Vanille', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('lemon-hydro-indoor-cbd::2g', 10, 0, 'Lemon Hydro Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('lemon-hydro-indoor-cbd::4g', 10, 0, 'Lemon Hydro Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('lemon-hydro-indoor-cbd::8g', 10, 0, 'Lemon Hydro Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('luxe-xr-max-2-vaporesso', 10, 0, 'Luxe XR Max 2 - Vaporesso', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('melange-vegetal-bergamote', 10, 0, 'Mélange végétal Bergamote', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('melange-vegetal-menthe', 10, 0, 'Mélange végétal Menthe', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('melange-vegetal-natura', 10, 0, 'Mélange végétal Natura', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('melon-fraise-des-bois-frais', 10, 0, 'Melon – Fraise des Bois FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('menthe-intense', 10, 0, 'Menthe Intense', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('moby-dick-hydro-indoor-cbd::2g', 10, 0, 'Moby Dick Hydro Indoor CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('moby-dick-hydro-indoor-cbd::4g', 10, 0, 'Moby Dick Hydro Indoor CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('moby-dick-hydro-indoor-cbd::8g', 10, 0, 'Moby Dick Hydro Indoor CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('moon-rock-cbd-indoor::2g', 10, 0, 'Moon Rock CBD Indoor — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('moon-rock-cbd-indoor::4g', 10, 0, 'Moon Rock CBD Indoor — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('moon-rock-cbd-indoor::8g', 10, 0, 'Moon Rock CBD Indoor — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('mousse-chocolat-blanc-noisettes-50-ml', 10, 0, 'Mousse Chocolat Blanc Noisettes – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('mure-myrtille-50ml-le-petit-verger', 10, 0, 'Mûre Myrtille 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('mure-myrtille-frais', 10, 0, 'Mûre – Myrtille FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('nectarine-fruit-du-dragon-50ml-le-petit-verger', 10, 0, 'Nectarine Fruit du Dragon 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('nectarine-fruit-du-dragon-frais', 10, 0, 'Nectarine – Fruit du Dragon FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('noisette', 10, 0, 'Noisette', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('palet-breton-50-ml', 10, 0, 'Palet Breton – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pasteque-citron-vert', 10, 0, 'Pastèque – Citron vert', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pasteque-melon-frais', 10, 0, 'Pastèque – Melon FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('peche-litchi-50ml-le-petit-verger', 10, 0, 'Pêche Litchi 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-beuz-arctic-grower', 10, 0, 'Plateau BEUZ – Arctic Grower', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-beuz-crazy-koala', 10, 0, 'Plateau BEUZ – Crazy Koala', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-beuz-purple-gorilla', 10, 0, 'Plateau BEUZ – Purple Gorilla', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-euphoria', 10, 0, 'Plateau Euphoria', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-gangsta-panda', 10, 0, 'Plateau Gangsta Panda', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr', 10, 0, 'Pod de Remplacement AeroX 32K – JNR', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-recharge', 10, 0, 'Pod Recharge', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pollen-d-amnesia-100-cbd::2g', 10, 0, 'Pollen D''Amnésia 100% CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pollen-d-amnesia-100-cbd::4g', 10, 0, 'Pollen D''Amnésia 100% CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pollen-d-amnesia-100-cbd::8g', 10, 0, 'Pollen D''Amnésia 100% CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pollen-d-or-100-cbd::2g', 10, 0, 'Pollen D''or 100% CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pollen-d-or-100-cbd::4g', 10, 0, 'Pollen D''or 100% CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pollen-d-or-100-cbd::8g', 10, 0, 'Pollen D''or 100% CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pomme-citron-50ml-le-petit-verger', 10, 0, 'Pomme Citron 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pomme-citron-frais', 10, 0, 'Pomme – Citron FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pomme-rouge-pomme-verte', 10, 0, 'Pomme rouge – Pomme verte', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('puff-30k-hyper-max-crown-bar-by-al-fakher', 10, 0, 'Puff 30k Hyper Max - Crown Bar by Al Fakher', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('puff-adalya-30k', 10, 0, 'PUFF Adalya 30K', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('raisin-rouge-grenade', 10, 0, 'Raisin rouge – Grenade', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('riz-au-lait-50-ml', 10, 0, 'Riz au Lait – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('robin-cherry-cbd::2g', 10, 0, 'Robin Cherry CBD — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('robin-cherry-cbd::4g', 10, 0, 'Robin Cherry CBD — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('robin-cherry-cbd::8g', 10, 0, 'Robin Cherry CBD — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('small-bud-lemon::2g', 10, 0, 'Small Bud Lemon — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('small-bud-lemon::4g', 10, 0, 'Small Bud Lemon — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('small-bud-lemon::8g', 10, 0, 'Small Bud Lemon — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('small-bud-strawberry::2g', 10, 0, 'Small Bud Strawberry — 2g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('small-bud-strawberry::4g', 10, 0, 'Small Bud Strawberry — 4g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('small-bud-strawberry::8g', 10, 0, 'Small Bud Strawberry — 8g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('snowing-in-dam', 10, 0, 'Snowing In Dam', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('spliff-box-l', 10, 0, 'Spliff Box L ! ?', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('spliff-box-m', 10, 0, 'Spliff Box M ! ?', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('starbuzz-ultra-max-25k', 10, 0, 'Starbuzz Ultra Max 25K', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('tiramisu-cafe-50-ml', 10, 0, 'Tiramisu Café – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('vaporesso-vibe-se-2', 10, 0, 'Vaporesso Vibe SE  2', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('vaporesso-vibe-se', 10, 0, 'Vaporesso Vibe SE', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('wiz', 10, 0, 'Sunakin Wiz Go', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('xros-5-mini-vaporesso', 10, 0, 'XROS 5 Mini Vaporesso', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('xros-5-vaporesso', 10, 0, 'XROS 5 Vaporesso', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('zpluse-jnr-42k', 10, 0, 'Zpluse JNR 42K+', unixepoch() * 1000);
