-- ═══════════════════════════════════════════════════════════════════════════
-- GÉNÉRÉ AUTOMATIQUEMENT par scripts/seed-stocks.js — ne pas éditer
-- 177 entrées de stock, 109 produits actifs
--
-- Rejouable sans risque : INSERT OR IGNORE laisse intacts les stocks déjà
-- présents. Ce fichier ne sert qu'à faire entrer les NOUVEAUX produits.
-- ═══════════════════════════════════════════════════════════════════════════

INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('al-fakher-50-k-prime', 63, 0, 'Al Fakher 50k ', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('allume-charbon-chicha-tsar', 10, 0, 'Allume charbon Chicha Tsar', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('allume-charbon-gaz-blackcoco-s', 10, 0, 'Allume charbon Gaz Blackcoco’s', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('amazonien', 10, 0, 'Amazonien', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('amnesia-hydro-indoor-cbd', 250, 0, 'Amnésia Hydro Indoor CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('ananas-coco-50ml-le-petit-verger', 10, 0, 'Ananas Coco 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('ananas-coco-frais', 10, 0, 'Ananas Coco FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('baba-au-rhum-50-ml', 10, 0, 'Baba au Rhum – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('balance-de-precision-hudson-300g-x-0-01g', 10, 0, 'Balance de précision HUDSON 300g x 0.01g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('balance-de-precision-java-100g-x-0-01g', 10, 0, 'Balance de précision JAVA 100g x 0.01g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('bang-en-verre-30-cm-percolateur', 10, 0, 'Bang en Verre 30 cm Percolateur', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('bang-verre-20-cm-percolateur', 10, 0, 'Bang verre 20 cm Percolateur', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('base-neutre-aromazon-vbase-50-50-1l-sans-nicotine', 10, 0, 'Base Neutre Aromazon VBASE 50/50 – 1L (Sans Nicotine)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('box-erato-230-smoktech', 10, 0, 'Box Erato 230 – Smoktech', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('box-gen-se-vaporesso', 10, 0, 'Box Gen SE Vaporesso', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('box-voopoo-vinci-spark-100', 10, 0, 'Box Voopoo Vinci Spark 100', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('brugnon-orange-sanguine-50-ml', 10, 0, 'Brugnon – Orange sanguine 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cake-noisettes-50-ml', 10, 0, 'Cake Noisettes – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cannele-50-ml', 10, 0, 'Cannelé – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cassis-framboise-50ml-le-petit-verger', 10, 0, 'Cassis Framboise 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cassis-framboise-frais', 10, 0, 'Cassis Framboise FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cassis', 10, 0, 'Cassis', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cendrier-alien', 10, 0, 'Cendrier Alien', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cendrier-astronaute', 10, 0, 'Cendrier Astronaute', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('cerise-pasteque-frais', 10, 0, 'Cerise Pastéque FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('charas-cbd', 10, 0, 'Charas CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('clearomiseur-zeus-nano-2-geekvape', 10, 0, 'Clearomiseur Zeus Nano 2 GeekVape', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('clearomiseur-zeus-subohm-5-ml-geekvape', 10, 0, 'Clearomiseur Zeus Subohm 5 ml Geekvape', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('concentre-biggy-bear-30ml', 10, 0, 'Concentré Biggy bear 30ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('corossol-peche-frais', 10, 0, 'Corossol Pêche FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('drizzle-in-dam-hydro-indoor-cbd', 140, 0, 'Drizzle In Dam Hydro Indoor (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-cg-50ml', 10, 0, 'E-CG 50ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Myrtille Framboise acidulée', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Myrtille Framboise acidulée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Cerise bleue Cranberry', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Cerise bleue Cranberry', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Cerise glacée', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Cerise glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Ananas Mangue Pastèque Passion', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Ananas Mangue Pastèque Passion', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Myrtille Framboise Cerise', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Myrtille Framboise Cerise', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Pastèque Mangue Pêche', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Pastèque Mangue Pêche', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Fraise Kiwi', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Fraise Kiwi', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Mangue Fruit de la passion', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Mangue Fruit de la passion', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Mûre Framboise', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Mûre Framboise', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Myrtille Grenade glacée', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Myrtille Grenade glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Pomme verte Pêche', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Pomme verte Pêche', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Cerise pastèque glacée', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Cerise pastèque glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Pêche Fruits des bois', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Pêche Fruits des bois', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Pastèque Chewing-gum', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Pastèque Chewing-gum', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Cola Cerise', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Cola Cerise', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Fraise glacée', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Fraise glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Mûre Fruit du dragon frais', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Mûre Fruit du dragon frais', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Pêche glacée', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Pêche glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Myrtille Cerise', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Myrtille Cerise', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Fruits rouges', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Fruits rouges', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Pastèque glacée', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Pastèque glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('e-liquide-jnr-10ml-20mg-sel-de-nicotine::Pastèque Fraise glacée', 10, 0, 'E-liquide JNR 10ml - 20mg sel de nicotine — Pastèque Fraise glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('eclair-vanille-50-ml', 10, 0, 'Éclair Vanille – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('extract-crumble', 10, 0, 'Extract Crumble (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('frais-peche-litchi-frais', 10, 0, 'Frais Pêche – Litchi FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fraise-litchi', 10, 0, 'Fraise – Litchi', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fraise-poire-50ml-le-petit-verger', 10, 0, 'Fraise Poire 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fraise-poire-frais', 10, 0, 'Fraise Poire FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fraise', 10, 0, 'Fraise', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fruit-du-dragon-fruits-rouges-frais', 10, 0, 'Fruit Du Dragon - Fruits Rouges FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fruit-du-dragon-jaune-framboise-bleue-frais', 10, 0, 'Fruit du Dragon Jaune – Framboise Bleue FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fruit-du-serpent-grenade-frais', 10, 0, 'Fruit du Serpent – Grenade FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('fruits-rouges', 10, 0, 'Fruits rouges', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('garlic-hydro-indoor-cbd', 69, 0, 'Garlic Hydro Indoor CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('geekvape-zeus-nano-3', 10, 0, 'Geekvape Zeus Nano 3', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('goyave-coco', 10, 0, 'Goyave - coco', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('grinder-champignon-3-parties-metal-effet-holographique', 10, 0, 'Grinder Champignon – 3 parties métal effet holographique', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('grinder-gold', 10, 0, 'Grinder Gold', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('grinder-sensky-4-parties-en-aluminium', 10, 0, 'Grinder Sensky – 4 parties en aluminium', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('hash-primero', 10, 0, 'Hash Primero (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jack-herer-hydro-indoor-cbd', 10, 0, 'Jack Herer Hydro Indoor CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jnr-32000-puffs::Cherry ICE', 21, 0, 'JNR Aero x 32000 Puffs — Cherry ICE', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jnr-32000-puffs::Blueberry Raspberry Cherry', 26, 0, 'JNR Aero x 32000 Puffs — Blueberry Raspberry Cherry', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jnr-32000-puffs::Watermelon Mango Peach', 26, 0, 'JNR Aero x 32000 Puffs — Watermelon Mango Peach', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jnr-32000-puffs::Black Dragon ice', 20, 0, 'JNR Aero x 32000 Puffs — Black Dragon ice', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('jnr-32000-puffs::Fizzi Cherry Cola', 19, 0, 'JNR Aero x 32000 Puffs — Fizzi Cherry Cola', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kit-box-gen-se-vaporesso-clearomiseur-zeus-nano-2-geek-vape', 10, 0, 'Kit Box Gen SE Vaporesso + Clearomiseur Zeus Nano 2 Geek Vape', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kit-gtx-one-pro-vaporesso', 10, 0, 'Kit GTX One Pro Vaporesso', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kit-q16-pro-plus-de-justfog', 10, 0, 'Kit Q16 Pro Plus de Justfog', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kiwi-cactus-frais', 10, 0, 'Kiwi – Cactus FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kiwi-mangue-50ml-le-petit-verger', 10, 0, 'Kiwi Mangue 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('kiwi-mangue-frais', 10, 0, 'Kiwi – Mangue FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('l-elixir', 10, 0, 'L''elixir', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-druide', 10, 0, 'Le Druide', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-menthe-verte', 10, 0, 'Le Menthe Verte', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-peche', 10, 0, 'Le Pêche', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-texan', 10, 0, 'Le Texan', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('le-vanille', 10, 0, 'Le Vanille', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('lemon-hydro-indoor-cbd', 10, 0, 'Lemon Hydro Indoor CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('luxe-xr-max-2-vaporesso', 10, 0, 'Luxe XR Max 2 - Vaporesso', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('mango-small-bud-cbd', 113, 0, 'Mango Small Bud CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('melange-vegetal-bergamote', 10, 0, 'Mélange végétal Bergamote 20g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('melange-vegetal-menthe', 10, 0, 'Mélange végétal Menthe', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('melange-vegetal-natura', 10, 0, 'Mélange végétal Natura 20g', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('melon-fraise-des-bois-frais', 10, 0, 'Melon – Fraise des Bois FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('menthe-intense', 10, 0, 'Menthe Intense', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('moby-dick-hydro-indoor-cbd', 10, 0, 'Moby Dick Hydro Indoor CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('moon-rock-cbd-indoor', 63, 0, 'Moon Rock CBD Indoor (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('mousse-chocolat-blanc-noisettes-50-ml', 10, 0, 'Mousse Chocolat Blanc Noisettes – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('mure-myrtille-50ml-le-petit-verger', 10, 0, 'Mûre Myrtille 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('mure-myrtille-frais', 10, 0, 'Mûre – Myrtille FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('nectarine-fruit-du-dragon-50ml-le-petit-verger', 10, 0, 'Nectarine Fruit du Dragon 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('nectarine-fruit-du-dragon-frais', 10, 0, 'Nectarine – Fruit du Dragon FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('noisette', 10, 0, 'Noisette', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('palet-breton-50-ml', 10, 0, 'Palet Breton – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pasteque-citron-vert', 10, 0, 'Pastèque – Citron vert', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pasteque-melon-frais', 10, 0, 'Pastèque – Melon FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('peche-litchi-50ml-le-petit-verger', 10, 0, 'Pêche Litchi 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-beuz-arctic-grower', 10, 0, 'Plateau BEUZ – Arctic Grower', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-beuz-crazy-koala', 10, 0, 'Plateau BEUZ – Crazy Koala', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-beuz-purple-gorilla', 10, 0, 'Plateau BEUZ – Purple Gorilla', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-euphoria', 10, 0, 'Plateau Euphoria', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('plateau-gangsta-panda', 10, 0, 'Plateau Gangsta Panda', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Mint', 26, 0, 'Pod Al Fakher 50K — Mint', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Menthol', 36, 0, 'Pod Al Fakher 50K — Menthol', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Spearmint', 54, 0, 'Pod Al Fakher 50K — Spearmint', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Lush Ice', 58, 0, 'Pod Al Fakher 50K — Lush Ice', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Ice Blue', 25, 0, 'Pod Al Fakher 50K — Ice Blue', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Gum Mint', 45, 0, 'Pod Al Fakher 50K — Gum Mint', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Lemon Mint', 45, 0, 'Pod Al Fakher 50K — Lemon Mint', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Blueberry Mint', 46, 0, 'Pod Al Fakher 50K — Blueberry Mint', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Blackcurrant Mint', 56, 0, 'Pod Al Fakher 50K — Blackcurrant Mint', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Lemon Lime', 54, 0, 'Pod Al Fakher 50K — Lemon Lime', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Lemon Lime Cherry Fizz', 43, 0, 'Pod Al Fakher 50K — Lemon Lime Cherry Fizz', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Blue Razz Lemonade', 56, 0, 'Pod Al Fakher 50K — Blue Razz Lemonade', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Blueberry Lemonade', 21, 0, 'Pod Al Fakher 50K — Blueberry Lemonade', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Berry Blue', 36, 0, 'Pod Al Fakher 50K — Berry Blue', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Blackcurrant Ice', 34, 0, 'Pod Al Fakher 50K — Blackcurrant Ice', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Blueberry Cherry', 32, 0, 'Pod Al Fakher 50K — Blueberry Cherry', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Blueberry Gum', 53, 0, 'Pod Al Fakher 50K — Blueberry Gum', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Blueberry Sour Raspberry', 34, 0, 'Pod Al Fakher 50K — Blueberry Sour Raspberry', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Cherry Fiesta', 36, 0, 'Pod Al Fakher 50K — Cherry Fiesta', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Cherry Ice', 35, 0, 'Pod Al Fakher 50K — Cherry Ice', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Mixed Berry', 58, 0, 'Pod Al Fakher 50K — Mixed Berry', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Strawberry Cherry', 24, 0, 'Pod Al Fakher 50K — Strawberry Cherry', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Strawberry Punch', 36, 0, 'Pod Al Fakher 50K — Strawberry Punch', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Watermelon Pineapple', 10, 0, 'Pod Al Fakher 50K — Watermelon Pineapple', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Watermelon Kiwi', 33, 0, 'Pod Al Fakher 50K — Watermelon Kiwi', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Watermelon Lime', 36, 0, 'Pod Al Fakher 50K — Watermelon Lime', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Watermelon Cherry', 10, 0, 'Pod Al Fakher 50K — Watermelon Cherry', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Fusion Pop (Cocktail fruité)', 36, 0, 'Pod Al Fakher 50K — Fusion Pop (Cocktail fruité)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Magic Love (Fruits exotiques)', 34, 0, 'Pod Al Fakher 50K — Magic Love (Fruits exotiques)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Mango Pineapple (Mangue Ananas)', 39, 0, 'Pod Al Fakher 50K — Mango Pineapple (Mangue Ananas)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Peach Ice', 28, 0, 'Pod Al Fakher 50K — Peach Ice', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Pineapple Ice (Ananas)', 30, 0, 'Pod Al Fakher 50K — Pineapple Ice (Ananas)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-al-fakher-50k::Summer Dream (Fruits d’été)', 38, 0, 'Pod Al Fakher 50K — Summer Dream (Fruits d’été)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Pastèque Glacée', 40, 0, 'Pod de Remplacement AeroX 32K – JNR — Pastèque Glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Fraise Glacée', 40, 0, 'Pod de Remplacement AeroX 32K – JNR — Fraise Glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Pêche Glacée', 40, 0, 'Pod de Remplacement AeroX 32K – JNR — Pêche Glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Pastèque Fraise', 40, 0, 'Pod de Remplacement AeroX 32K – JNR — Pastèque Fraise', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Fraise Kiwi', 40, 0, 'Pod de Remplacement AeroX 32K – JNR — Fraise Kiwi', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Pastèque Mangue Pêche', 40, 0, 'Pod de Remplacement AeroX 32K – JNR — Pastèque Mangue Pêche', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Pastèque Bubble-gum', 40, 0, 'Pod de Remplacement AeroX 32K – JNR — Pastèque Bubble-gum', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Fruits Rouges', 10, 0, 'Pod de Remplacement AeroX 32K – JNR — Fruits Rouges', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Myrtille Grenade Glacée', 10, 0, 'Pod de Remplacement AeroX 32K – JNR — Myrtille Grenade Glacée', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Pêche Fruit Rouges', 10, 0, 'Pod de Remplacement AeroX 32K – JNR — Pêche Fruit Rouges', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Coca Cerise', 10, 0, 'Pod de Remplacement AeroX 32K – JNR — Coca Cerise', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-de-remplacement-aerox-32k-jnr::Myrtille Framboise Cerise', 10, 0, 'Pod de Remplacement AeroX 32K – JNR — Myrtille Framboise Cerise', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pod-recharge', 10, 0, 'Pod Recharge', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pollen-d-amnesia-100-cbd', 10, 0, 'Pollen D''Amnésia 100% CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pollen-d-or-100-cbd', 10, 0, 'Pollen D''or 100% CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pomme-citron-50ml-le-petit-verger', 10, 0, 'Pomme Citron 50ml - Le Petit Verger', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pomme-citron-frais', 10, 0, 'Pomme – Citron FRAIS', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('pomme-rouge-pomme-verte', 10, 0, 'Pomme rouge – Pomme verte', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('raisin-rouge-grenade', 10, 0, 'Raisin rouge – Grenade', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('riz-au-lait-50-ml', 10, 0, 'Riz au Lait – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('smash-small-bud-cbd', 126, 0, 'Smash Small Bud CBD (vrac, en g)', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('spliff-box-l', 10, 0, 'Spliff Box L', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('spliff-box-m', 10, 0, 'Spliff Box M', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('tiramisu-cafe-50-ml', 10, 0, 'Tiramisu Café – 50 ml', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('vaporesso-vibe-se-2', 10, 0, 'Vaporesso Vibe SE  2', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('vaporesso-vibe-se', 10, 0, 'Vaporesso Vibe SE', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('wiz', 10, 0, 'Sunakin Wiz Go', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('xros-5-mini-vaporesso', 10, 0, 'XROS 5 Mini Vaporesso', unixepoch() * 1000);
INSERT OR IGNORE INTO stocks (cle, dispo, reserve, libelle, majLe) VALUES ('xros-5-vaporesso', 10, 0, 'XROS 5 Vaporesso', unixepoch() * 1000);
